/*
 * Copyright 2018 Coati Software KG
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef SOURCETRAIL_DEFINITION_KIND_H
#define SOURCETRAIL_DEFINITION_KIND_H

namespace sourcetrail
{
/**
 * Enum providing all possible values for a symbol's definition kind.
 *
 * The DefinitionKind specifies "how" a symbol is defined.
 * When recording the definition of a symbol, you would usually also record an explicit definition
 * kind. However, you may also want to record symbols that are implicitly generated by the compiler.
 * In this case you can record an implicit definition kind for those symbols. If you do not record
 * any definition kind for a symbol, Sourcetrail will show it as "non-indexed".
 */
enum class DefinitionKind : int
{
	IMPLICIT = 1,
	EXPLICIT = 2
};

int definitionKindToInt(DefinitionKind kind);
DefinitionKind intToDefinitionKind(int i);
}	 // namespace sourcetrail

#endif	  // SOURCETRAIL_DEFINITION_KIND_H
