#ifndef SOURCETRAIL_DEFINITION_KIND_H
#define SOURCETRAIL_DEFINITION_KIND_H

namespace sourcetrail
{
	/**
	* Enum providing all possible values for a symbol's definition kind.
	*
	* The DefinitionKind specifies "how" a symbol is defined.
	* When recording the definition of a symbol, you would usually also record an explicit definition kind.
	* However, you may also want to record symbols that are implicitly generated by the compiler. In this case you can
	* record an implicit definition kind for those symbols.
	* If you do not record any definition kind for a symbol, Sourcetrail will show it as "non-indexed".
	*/
	enum DefinitionKind
	{
		DEFINITION_IMPLICIT = 1,
		DEFINITION_EXPLICIT = 2
	};

	int definitionKindToInt(DefinitionKind v);
	DefinitionKind intToDefinitionKind(int v);
}

#endif // SOURCETRAIL_DEFINITION_KIND_H
